In [1]:
print("hello world")

hello world


In [2]:
!wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt

--2025-06-18 21:12:04--  https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8002::154, 2606:50c0:8003::154, 2606:50c0:8000::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8002::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1115394 (1.1M) [text/plain]
Saving to: 'input.txt'

     0K .......... .......... .......... .......... ..........  4%  649K 2s
    50K .......... .......... .......... .......... ..........  9% 2.63M 1s
   100K .......... .......... .......... .......... .......... 13% 1.03M 1s
   150K .......... .......... .......... .......... .......... 18% 5.48M 1s
   200K .......... .......... .......... .......... .......... 22% 1.28M 1s
   250K .......... .......... .......... .......... .......... 27% 7.35M 1s
   300K .......... .......... .......... .......... .......... 32% 4.32M 0s
   35

In [2]:
with open("input.txt","r",encoding="utf-8") as f:
    text = f.read()

In [3]:
print(text[:10])

First Citi


In [4]:
print(len(text))

1115394


In [5]:
chars = sorted(list(set(text)))

In [6]:
vocab_size = len(chars)

In [7]:
print(vocab_size)
print(''.join(chars))

65

 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz


In [8]:
#create a mapping from characters to integers
stoi= { ch:i for i,ch in enumerate(chars)}
itos = {i:ch for i,ch in enumerate(chars) }
encode =  lambda s: [stoi[c] for c in s]# encoder: take a string, output a list of integers
decode =  lambda l: ''.join([itos[i] for i in l])
print(encode("hii there"))
print(decode(encode("hii there")))

[46, 47, 47, 1, 58, 46, 43, 56, 43]
hii there


In [9]:
print(encode(" !$&"))

[1, 2, 3, 4]


In [10]:
print(decode(encode(" !$&")))

 !$&


In [11]:
import torch

C:\Users\pvvis\PycharmProjects\PythonProject3\.venv\Lib\site-packages\torch\_subclasses\functional_tensor.py:276: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\torch\csrc\utils\tensor_numpy.cpp:81.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


In [12]:
data = torch.tensor(encode(text), dtype=torch.long)

In [13]:
print(data.shape,data.type)

torch.Size([1115394]) <built-in method type of Tensor object at 0x00000234C5F74820>


In [14]:
print(data[:100])

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59])


In [15]:
n = int(0.9*len(data))
train_data = data[:n]
val_data = data[n:]

In [16]:
block_size = 8
train_data[:block_size+1]

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58])

In [17]:
x = train_data[:block_size]

In [18]:
torch.manual_seed(1337)
batch_size = 4
block_size = 8
def get_batch(split) :
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size,(batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x,y

In [19]:
xb,yb = get_batch('train')
print(xb.shape)
print(xb)
print(yb.shape)
print(yb)

torch.Size([4, 8])
tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])
torch.Size([4, 8])
tensor([[43, 58,  5, 57,  1, 46, 43, 39],
        [53, 56,  1, 58, 46, 39, 58,  1],
        [58,  1, 58, 46, 39, 58,  1, 46],
        [17, 27, 10,  0, 21,  1, 54, 39]])
